### ISSUE TITLE
Integración con Hive Warehouse Connector

### ISSUE THREAD

**Issue by jhosmanfrias** [HuemulSolutions/huemul-bigdatagovernance#109]
En algunas versiones de Hortonworks, por ejemplo, 3.1.0, la metadata de Hive y Spark, están separadas. Además, cuando una grilla se seguriza con Kerberos y SSL, no se encuentra forma factible de conectarse a Hive desde Spark con jdbc. Esto, genera complicaciones al momento de usar Huemul, ya que el framework gestiona metadata de tablas y en esta versión de Hortonworks, el manejo es doble. 

Por tanto, se requiere, ojalá, que Huemul soporte el conector Hortonworks Warehouse Connector (HWC)

**Comment by huemulDeveloper** [comment]
Para utilizar esta opción, se debe realizar lo siguiente:

1. Habilitar en globalSettings la opción de conexión usando HWC

```scala
   Global.externalBBDD_conf.Using_HWC.setActive(true)
```

2. Incluir driver y configuración de conexión en ejecución de spark-submit, el siguiente ejemplo grafica la forma de invocación

```scala
spark-submit ... --jars /usr/hdp/current/hive_warehouse_connector/hive-warehouse-connector-assembly-1.0.0.3.0.1.0-XX.jar  ... --conf "spark.sql.hive.hiveserver2.jdbc.url=jdbc:hive2://ambiente.hortonworks.com:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2;user=xxx;password=yyy"
```
donde XX es la versión específica del ambiente.

**Comment by jhosmanfrias** [comment]
Testeado en mi ambiente y ok con las pruebas.
