### ISSUE TITLE
Customizar nombre columnas de control de tablas tipo Master/Reference/Transaccional

### ISSUE THREAD

**Issue by christian-sattler** [HuemulSolutions/huemul-bigdatagovernance#112]
**Is your feature request related to a problem? Please describe.**
Para el cumplimiento de estandares y concivencia con tablas ya existente que se desaean cargar desde del framework, se encesita que las columnas de control mdm_fhnew, mdm_processnew, mdm_fhchange, mdm_processchange, mdm_statusreg y mdm_hash

**Describe the solution you'd like**
Poder denifir a nivel de tabla o grobal setting los nombres de las columnas y en el caso de las tablas maestras modificar el codio para registro activo y eliminado

**Additional context**

**Comment by huemulDeveloper** [comment]
Creación de nuevos métodos en huemul_table para incluir nombres customizados a los campos de trazabilidad de cambios.

* **setNameForMDM_fhChange(value: String):** permite asignar el nombre al campo que registra la fecha y hora de cambio en algún dato a nivel de fila. Solo tiene efecto en tablas de tipo "master" y "reference"
* **setNameForMDM_fhNew(value: String):** permite asignar el nombre al campo que registra la fecha y hora en que se agregó la fila en la tabla. Aplica a todos los tipos de tabla
* **setNameForMDM_ProcessNew(value: String):** permite asignar el nombre al campo que registra el proceso que agregó la fila. Aplica para todos los tipos de tabla.
* **setNameForMDM_ProcessChange(value: String):** permite asignar el nombre al campo que registra el proceso que hizo algún cambio en la fila. Solo tiene efecto en tablas de tipo "master" y "reference"
* **setNameForMDM_hash(value: String):** permite asignar el nombre al campo que calcula el valor Hash de la fila. Aplica para todos los tipos de tabla.
* **setNameForMDM_StatusReg(value: String):** permite asignar el nombre al campo que indica el status de la fila (agregada, modificada o eliminada). Solo tiene efecto en tablas de tipo "master" y "reference"

El siguiente ejemplo en scala muestra la forma de usar al definir una tabla
```scala
class tbl_cliente (HuemulLib: huemul_BigDataGovernance, Control: huemul_Control) extends huemul_Table(HuemulLib,Control) with Serializable {

... 

    this.setNameForMDM_fhChange("customNameDtChange")
    this.setNameForMDM_fhNew("customNameDtNew")
    this.setNameForMDM_ProcessNew("customNameProcessNew")
    this.setNameForMDM_ProcessChange("customNameProcessChange")
    this.setNameForMDM_hash("customNameHash")
    this.setNameForMDM_StatusReg("customNameStatus")

...

}
```
