### ISSUE TITLE
(P) Agregar campo con Info de DataQuality

### ISSUE THREAD

**Issue by huemulDeveloper** [HuemulSolutions/huemul-bigdatagovernance#13]
Cuando se aplica DataQuality con warnings, el resultado de cada fila/campo se pierde (no se guarda en ninguna parte).

La idea de esta nueva funcionalidad es crear un campo en las tablas maestras y transaccionales, que permita agregar los warnings de dataquality, el campo se llamaría MDM_DataQualityResult y guardaría la información de la siguiente forma: [[NombreCampo]]=ReglaDQ;[[Nombrecampo2]]=OtraReglaDQ;[[NombreTabla]]=ReglaDQTabla

Si el campo está poblado, es porque alguna regla no se cumplió.

Las reglas solo se pueden guardar a nivel de filas, a nivel agrupado no tiene sentido, ya que todas las filas tendrían esa regla repetida

**Comment by sebasrod** [comment]
Se descarta, el detalle se guardará en una nueva tabla específica para errores de DQ
