### ISSUE TITLE
(P) Agregar Nivel de compresión en Tablas

### ISSUE THREAD

**Issue by huemulDeveloper** [HuemulSolutions/huemul-bigdatagovernance#14]
Al almacenar la información en HDFS no se está especificando el nivel de compresión (se deja el que trae por default).

Se debe agregar esta característica, para que los usuarios la definan.

Si no se especifica, el comportamiento debe ser el mismo que el actual (el default definido por la configuración).

**Comment by sebasrod** [comment]
Se descarta, se puede configurar a nivel de spark.
