### ISSUE TITLE
(P) Backup de tablas maestras

### ISSUE THREAD

**Issue by huemulDeveloper** [HuemulSolutions/huemul-bigdatagovernance#16]
Dado que los catálogos maestros son imprescindibles para la gestión de la organización, es importante mantener N cantidad de copias de seguridad. Estas copias pueden ser restituidas en caso de procesamiento erroneo.

Actualmente se guarda la última versión en la carpeta temporal, lo ideal sería tener una carpeta de backup configurada en GlobalSettings, o en su defecto generar un archivo de backup en la misma ruta donde está el archivo vigente (evaluar qué es mejor), y además agregar un campo en la tabla control_tables que indique el N° de copias de seguridad, y crear una tabla en PostgreSQL que administre estas versiones, así se puede ir eliminando las versiones más antiguas.

**Comment by sebasrod** [comment]
Para usar esta nueva funcionalidad en las tablas de tipo Master y Reference, se deben implementa las siguientes modificaciones sobre el código.

1. GobalSettings: Por default está habilitada la opción de guardar backup, por ello se debe incluir el path donde se almacenarán los archivos de backup, ejemplo:
```scala
Global.MDM_Backup_Path.append(new huemul_KeyValuePath("production","hdfs:///user/data/production/backup/"))
```

Para deshabilitar la opción, se debe indicar lo siguiente en GobalSettings:
```scala
Global.MDM_SaveBackup = false
```

2. Habilitar en cada tabla: Por default esta opción está deshabilitada en cada tabla, por tanto se debe indicar en forma explícita.

```scala
class tbl_DatosBasicos(HuemulLib: huemul_BigDataGovernance, Control: huemul_Control) extends huemul_Table(HuemulLib,Control) with Serializable {
  ...
  this.setSaveBackup(true)
   ...

  this.ApplyTableDefinition()
}
```

## Compatibilidad con versiones anteriores
Para hacer el upgrade desde la versión 1.4.1, se deben ejecutar los script de actualización, específicamente lo siguiente:

1. Actualización del modelo de control: Ejecutar el siguiente script en Postgres
```postgres
\i huemul_bdg_upgrade_1.4_to_2.0.sql
```

La sección del script que aplica este cambio contiene lo siguiente:
```sql
alter table control_tables add table_backup		 	  int;
alter table control_tablesuse add tableuse_pathbackup	  varchar(1000);
```
