### ISSUE TITLE
Agregar SandBox de áreas específicas

### ISSUE THREAD

**Issue by huemulDeveloper** [HuemulSolutions/huemul-bigdatagovernance#20]
Agregar 
SandBox_Risk
SandBox_MIS
SandBox_Commercial
SandBox_Finance
SandBox_Op

**Comment by sebasrod** [comment]
Se determina que no son necesarias, puesto que se pueden abrir tantos sandbox como tipos de areas existan, lo mejor es incluirlo en el GlobalSettings particular de cada implementacion.
