### ISSUE TITLE
Parametrizar los nombres de las reglas de DQ para PK y FK

### ISSUE THREAD

**Issue by jhosmanfrias** [HuemulSolutions/huemul-bigdatagovernance#73]
Existen reglas de Data Quality autogeneradas, las cuales no llevan un nombre de negocio asociado

La idea de esta nuevo feature es que se permita parametrizar con un nombre o código de negocio asociado a las reglas de data quality relacionadas con las PK y FK.

Para lograr esto, debe existir un método para setear el nombre o código de negocio. O reutilizar alguno existente, generando una sobrecarga de método.

La necesidad de este feature radica en que se debe generar estadísticas de las reglas de calidad asociadas a un modelo de control de calidad, el cual indexa las reglas mediante códigos únicos con sentido para el negocio.

**Comment by sebasrod** [comment]
Se implementan los siguientes métodos:

### Clase huemul_Columns

* **setIsUnique(externalCode: String = null): huemul_Columns**: Indica que campo es parte de la PK, y en parámetro indica código externo. Este método reemplazará al método setIsUnique(value: Boolean), el cual será deprecado en la versión 3.0
* **setNullable(externalCode: String = null): huemul_Columns**: Indica que campo permite nulos, y en parámetro indica código externo. Este método reemplazará al método setNullable(value: Boolean), el cual será deprecado en la versión 3.0
* **setDQ_MinLen(value: Integer, externalCode: String = null): huemul_Columns**: Indica el largo mínimo del campo, en el segundo parámetro indica código externo. Este método reemplazará al método setDQ_MinLen(value: Integer), el cual será deprecado en la versión 3.0
* **setDQ_MaxLen(value: Integer, externalCode: String = null): huemul_Columns**: Indica el largo máximo del campo, en el segundo parámetro indica código externo. Este método reemplazará al método setDQ_MaxLen(value: Integer), el cual será deprecado en la versión 3.0
* **setDQ_MinDecimalValue(value: Decimal, externalCode: String = null): huemul_Columns**: Indica el valor decimal mínimo para el campo, en el segundo parámetro indica código externo. Este método reemplazará al método setDQ_MinDecimalValue(value: Decimal), el cual será deprecado en la versión 3.0
* **setDQ_MaxDecimalValue(value: Decimal, externalCode: String = null): huemul_Columns**: Indica el valor decimal máximo para el campo, en el segundo parámetro indica código externo. Este método reemplazará al método setDQ_MaxDecimalValue(value: Decimal), el cual será deprecado en la versión 3.0
* **setDQ_MinDateTimeValue(value: String, externalCode: String = null): huemul_Columns**: Indica el valor mínimo de fecha y hora aceptado, en el segundo parámetro indica código externo. Este método reemplazará al método setDQ_MinDateTimeValue(value: String), el cual será deprecado en la versión 3.0
* **setDQ_MaxDateTimeValue(value: String, externalCode: String = null): huemul_Columns**: Indica el valor máximo de fecha y hora aceptado, en el segundo parámetro indica código externo. Este método reemplazará al método setDQ_MaxDateTimeValue(value: String), el cual será deprecado en la versión 3.0

### Clase huemul_Table

* **setPK_externalCode(value: String)**: Indica el código externo para indicar la validación de PK sobre la tabla.

### Clase huemul_Table_Relationship

* **setExternalCode(value: String): huemul_Table_Relationship**: Indica el código externo para indicar la validación de FK.

Ejemplo: 
```scala
  val itbl_DatosBasicos = new tbl_DatosBasicos(HuemulLib,Control)
  val fk_tbl_DatosBasicos = new huemul_Table_Relationship(itbl_DatosBasicos, false).setExternalCode("USER_FK_CODE")
  fk_tbl_DatosBasicos.AddRelationship(itbl_DatosBasicos.TipoValor , TipoValor)
```

**Comment by sebasrod** [comment]
Terminado

**Comment by jhosmanfrias** [comment]
Buena!!! Trabajo en equipo xD jaja
