### ISSUE TITLE
Nuevo tipo de formato (CSV) en la escritura

### ISSUE THREAD

**Issue by jhosmanfrias** [HuemulSolutions/huemul-bigdatagovernance#80]
Es necesario contar con un nuevo formato que permita escribir en HDFS archivos CSV.

El objetivo de este nuevo requerimiento se basa en la necesidad de exportar en archivos planos y legibles por humano, como lo es CSV.

Para lograr esto, se propone agregar en la clase huemulType_StorageType, un valor más a la variable enumerado:

Por ejemplo:

package com.huemulsolutions.bigdata.tables

```
object huemulType_StorageType extends Enumeration {
  type huemulType_StorageType = Value
  val PARQUET, ORC, AVRO, CSV = Value
}
```

**Comment by sebasrod** [comment]
la clase huemulType_StorageType se utiliza para especificar el tipo de almacenamiento de una tabla. Entiendo que para exportar los datos no se requiere necesariamente generar una tabla, sino que se puede exportar un DF, para ello es posible utilizar las funciones directas desde spark...

¿esto se requiere solo para exportar datos o para guardar una tabla en formato csv?
¿en qué caso sería bueno guardar una tabla en formato CSV?

**Comment by jhosmanfrias** [comment]
¿esto se requiere solo para exportar datos o para guardar una tabla en
formato csv? Ambas. Pero el requerimiento como tal es para exportar los
datos. Estos datos deben ser enviados a un departamental (caso CdN), por
ejemplo. Por otro lado, como esta "masterización" generará en reporting
tablones (caso IFRS)… pensé sería bueno poder usar los tablones desde Hive
reporting y también tenerlos para moverlos a otro servidor.

¿en qué caso sería bueno guardar una tabla en formato CSV?
En caso IFRS (comentado anteriormente). A menos que se pueda guardar el
tablón en formato parquet pero a la vez deje en otra ruta el CSV (como lo
hicimos en bbva).

El tema es que no queríamos pasar a llevar a Huemul. Si podemos usar
funciones spark nos avisas entonces.

**Comment by sebasrod** [comment]
Se cierra debido a que se puede exportar directamente.
